#!/bin/bash
# service script to start/stop webservice_fib
#
# chkconfig: 35 80 30
# pidfile: /var/run/webservice_fib.pid
#
### BEGIN INIT INFO
# Provides: webservice_fib
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Start:
# Required-Stop:
# Default-Start: 3 5
# Default-Stop: 0 1 2 4 6
### END INIT INFO

servicename="webservice_fib"
programname="httpserverthread.py"
lockfile="/var/lock/subsys/webservice_fib"
pidfile="/var/run/webservice_fib.pid"

start() {
    echo -n "Starting $servicename "
    if [ -f $lockfile ]; then
        echo "Service already started, stop it first"
        RETVAL=1
        return
    fi

    start_daemon -p $pidfile /var/webservice/$programname 
    #/root/rocc/$programname
    RETVAL=$?

    if [ $RETVAL -eq 0 ]; then
        pid=`ps ax|grep httpserv|grep -v grep|cut -d ' ' -f 1`
        touch $lockfile
       
        echo success
    else
        echo failure
    fi
}

stop() {
    echo -n "Shutting down $servicename "
    killproc -p $pidfile $programname
    rm -f $lockfile $pidfile
    echo success
    RETVAL=0
}

status() {
    n=`ps ax|grep $programname|grep -v grep|wc -l` 
    if [ $n -gt 0 ];then
        echo $servicename is running
    else
        echo $servicename is stopped
    fi
}


case "$1" in
    start)
        start $2
        ;;

    stop)
        stop
        ;;

    restart)
        stop
        sleep 1
        start
        ;;

    status)
        status
        RETVAL=$?
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}"
        ;;
esac

exit $RETVAL
